#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_USER=pi
readonly TARGET_PATH=/home/pi/desk_controller
readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/debug/desk_controller

cross build --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_USER}@${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_USER}@${TARGET_HOST} ${TARGET_PATH}
